jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          # Mapping GitHub Secrets to Env Vars that Spring Boot recognizes
          DB_URL: ${{ secrets.DATASOURCE_URL }}
          DB_USER: ${{ secrets.DATASOURCE_USER }}
          DB_PASS: ${{ secrets.DATASOURCE_PASS }}
