spring:
  datasource:
    url: ${DATASOURCE_URL_STAGING}
    username: ${DATASOURCE_USER_STAGING}
    password: ${DATASOURCE_PASS_STAGING}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        temp:
          use_jdbc_metadata_defaults: false
custom:
  api-key: ${API_KEY}
