spring:
  datasource:
    url: ${DATASOURCE_URL_DEV}
    username: ${DATASOURCE_USER_DEV}
    password: ${DATASOURCE_PASS_DEV}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
custom:
  api-key: ${API_KEY}
