spring:
  datasource:
    url: jdbc:postgresql://ep-old-term-a1lzy708-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&ssl=true
    username: neondb_owner
    password: npg_8Qehu3WVZpiL
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        temp:
          use_jdbc_metadata_defaults: false    

custom:
  api-key: ${API_KEY}
