spring:
  datasource:
    url: ${{ secrets.DATASOURCE_URL }}
    username: ${{ secrets.DATASOURCE_USER }}
    password: ${{ secrets.DATASOURCE_PASS }}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        temp:
          use_jdbc_metadata_defaults: false
          
